- name: uninstall nginx clean
  hosts: nginx
  become: yes
  tasks:
    - name: stop and disable nginx service
      service:
        name: nginx
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: purge nginx and related packages
      apt:
        name:
          - nginx
          - nginx-common
        state: absent
        purge: yes
        autoremove: yes
        update_cache: yes

    - name: remove nginx landing page
      file:
        path: /var/www/html/index.html
        state: absent

- name: remove ssl directory
  hosts: nginx-main
  become: yes
  tasks:
    - name: remove ssl directory
      file:
        path: /etc/nginx/ssl
        state: absent