- name: create openssl
  hosts: nginx-main
  become: yes
  vars_files:
    - vars.yml   
  tasks:
    - name: create ssl self signed
      shell: |
        mkdir -p /etc/nginx/ssl && \
        openssl req -x509 -nodes -days 365 \
          -newkey rsa:2048 \
          -keyout {{ ssl_certificate_key }} \
          -out {{ ssl_certificate }} \
          -subj "/C=ID/ST=Jakarta/L=Jakarta/O=Localhost/CN=localhost"
#      args:
#        creates: /etc/nginx/ssl/selfsigned.crt

- name: install nginx
  hosts: nginx
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

- name: Setup nginx.conf with upstream backend cluster
  hosts: nginx-main
  become: yes
  vars_files:
    - vars.yml  
  tasks:
    - name: Generate nginx config from template
      template:
        src: templates/nginx_selfsigned.j2
        dest: /etc/nginx/sites-available/nginx_selfsigned
        owner: root
        group: root
        mode: '0644'

    - name: create symlink nginx_selfsigned
      file:
        src: /etc/nginx/sites-available/nginx_selfsigned
        dest: /etc/nginx/sites-enabled/nginx_selfsigned
        state: link

    - name: validasi config nginx
      command: nginx -t
      register: nginx_test_result

    - name: result config validasi
      debug:
        msg: "{{ nginx_test_result.stdout_lines }}"

    - name: restart nginx
      command: systemctl reload nginx

- name: Setup landing page
  hosts: nginx
  become: yes
  tasks:
    - name: Create landing page HTML
      copy:
        content: "Welcome this from {{ ansible_host }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'